---
title: "Solutions_Ramon_Schildknecht_RTP Excercise Sheet - Series 1"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tseries)
library(tidyverse)
library(plotly)
library(timetk)
```


# Series 1

## Exercice 1.1 - backward differencing

```{r}
set.seed(22)
# Apply backward differencing on a timeseries created by the following model:
# create timeseries object
t <- seq(1, 100, length = 100)
data <- 2 * t + 0.5 + runif(100, -5, 5)
ts <- ts(data)
# backward differencing
ts_diff <- diff(ts)
# compare lengths of arrays with
print("length difference:")
(length_diff <- length(ts) - length(ts_diff))
# adf.test(ts) # be careful!
plot(ts)
plot(ts_diff)
```

## Exercice 1.2 - remove linear trend
a)

```{r}
# create reusable function
generate_and_plot_ts <- function(model) {
  set.seed(22)
  t <- seq(1, 100, length = 100)
  data <- model
  ts <- ts(data)
  
  # backward differencing
  ts_diff <- diff(ts)
  plot(ts)
  plot(ts_diff)
}
```


```{r}
generate_and_plot_ts(0.5*t + 1 + runif(100, -1, 1))
```


b)
```{r}
generate_and_plot_ts(2*t^2 + 3*t + runif(100, -200, 200))
```


## Exercice 1.3

```{r}
d <- co2
glimpse(d)
head(d)
tail(d)
# already a time series object!
# ts <- ts(d, start = 1959, end = 1998, frequency = 12)
plot(co2, main = "co2 data")

# generate interactive plot
d_index <- tk_index(d)
(p <- plot_ly(x = ~d_index, y = ~d, mode = 'lines'))

acf(d)
pacf(d)
# try and error
# d_diff <- (diff(d, lag = 1))
# d_diff2 <- (diff(d_diff, lag = 1))
# d_diff3 <- (diff(d_diff2, lag = 1))
# d_diff4 <- (diff(d_diff3, lag = 1))
# d_diff5 <- (diff(d_diff4, lag = 1))

# 5 differences is optimal
d_diff <- (diff(d, lag = 1, differences = 5))
acf(d_diff)
pacf(d_diff)

# check result with interactive plot
d_diff_index <- tk_index(d_diff)
(p2 <- plot_ly(x = ~d_diff_index, y = ~d_diff, mode = 'lines'))
# success!
```


## Exercice 1.4

```{r}
# hier weiter
```

## Exercice 1.5

```{r}

```

## Exercice 1.6

```{r}

```

## Exercice 1.7

```{r}

```

## Exercice 1.8

```{r}

```

